import { ForgiatoColumn } from "./forgiatiColumns";

export const tubiColumns: ForgiatoColumn[] = [
  { field: "Title", label: "Codice / Title", width: "200px" },
  { field: "CodiceSAM", label: "Codice SAM" },
  { field: "field_1", label: "TIPO" },
  { field: "field_2", label: "N° ORDINE" },
  { field: "field_3", label: "DATA OD", type: "date" },
  { field: "field_4", label: "FORNITORE" },
  { field: "field_5", label: "P." },
  { field: "field_6", label: "Q.tà." },
  { field: "field_7", label: "Lungh. Tubo (m)" },
  { field: "field_8", label: 'DN (")' },
  { field: "field_9", label: "DN (mm)" },
  { field: "field_10", label: "SP" },
  { field: "field_11", label: "GRADO" },
  { field: "field_12", label: "PSL1/ PSL2" },
  { field: "field_13", label: "PED" },
  { field: "field_14", label: "HIC" },
  { field: "field_15", label: "N° Bolla" },
  { field: "field_16", label: "DATA CONSEGNA", type: "date" },
  { field: "field_17", label: "N° CERT." },
  { field: "field_18", label: "N° COLATA" },
  { field: "field_19", label: "GIACENZA(mm) CONTAB." },
  { field: "field_20", label: "GIACENZA(mm) NON TAGLIATO" },
  { field: "field_21", label: "DATA ULTIMO PRELIEVO", type: "date" },
  { field: "field_22", label: "Prezzo kg/mt" },
  { field: "field_23", label: "Prezzo metro" },
  { field: "field_24", label: "Acquistato Curatore" },
  { field: "field_25", label: "No. Commessa" },
  { field: "field_26", label: "Esubero" },
  { field: "field_27", label: "RITARDO" },
  { field: "Modified", label: "Data/ora modifica", type: "date" },
];
